//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoggerDetail
    {
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CostID { get; set; }
        public Nullable<int> IDMA { get; set; }
        public Nullable<int> IDSA { get; set; }
        public Nullable<int> Duration { get; set; }
        public string ProjectSite { get; set; }
        public Nullable<System.DateTime> LogDetDate { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
    }
}
