//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyData : DbContext
    {
        public MyData()
            : base("name=MyData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Logger> Loggers { get; set; }
        public virtual DbSet<MainActivity> MainActivities { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubActivity> SubActivities { get; set; }
        public virtual DbSet<LoggerDetail> LoggerDetails { get; set; }
        public virtual DbSet<vwLogDetail> vwLogDetails { get; set; }
    }
}
