//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLogDetail
    {
        public int LogID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> CostID { get; set; }
        public string CostCenter { get; set; }
        public Nullable<int> IDMA { get; set; }
        public string MainActivity { get; set; }
        public Nullable<int> IDSA { get; set; }
        public string SubActivity { get; set; }
        public string ProjectSite { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LogDetDate { get; set; }
    }
}
